export const ACCESS_TOKEN = "DRAGON_APP_ACCESS_TOKEN";
export const REFRESH_TOKEN = "DRAGON_APP_REFRESH_TOKEN";
export const DISTANCE_MATRIX = "DISTANCE_MATRIX";
export const GOOGLE_DISTANCE_MATRIX = "GOOGLE_DISTANCE_MATRIX";
